
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import "./Global.scss";
import Link from 'next/link';
import { SessionProvider } from "next-auth/react";
import NavBar from "./components/NavBar";
// import { SessionProvider } from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar></NavBar>
        <main>
        <SessionProvider>
        {children}
        </SessionProvider>
          

          
        </main>
        <footer>
          <p>© 2025 Stock Trading Platform by Leo Lau</p>
        </footer>
      </body>
    </html>
  );
}

