
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { SessionProvider } from "next-auth/react";
// import { SessionProvider } from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar></NavBar>
        <main>
        <SessionProvider>
        {children}
        </SessionProvider>
          

          
        </main>
        <footer>
          <p>© 2025 Stock Trading Platform by Leo Lau</p>
        </footer>
      </body>
    </html>
  );
}

function NavBar() {
  return (
    <nav className="bg-blue-600 p-4">
      <div className="container mx-auto flex justify-between items-center">
      <header>
        <nav>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/stock">Stock</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/user">User</a></li>
            <li><a href="/contact">Contact</a></li>
            <li><a href="/signin">SignIn</a></li>
            {/* Add more links as needed */}
          </ul>
        </nav>
      </header>
      </div>
      
    </nav>
  )

}