apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-env
  namespace: webapp
data:
  NODE_ENV: development
  # Example placeholders; override via kubectl create configmap ... --from-env-file=.env
  GOOGLE_API_KEY: changeme
  GITHUB_CLIENT_ID: changeme
  GITHUB_CLIENT_SECRET: changeme
  NEXTAUTH_SECRET: changeme
  NEXTAUTH_URL: http://localhost:3000
  MONGODB_URI: mongodb://localhost:27017/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: webapp-webapp:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: webapp-env
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: 150m
              memory: 512Mi
            limits:
              cpu: 750m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 30080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp
  namespace: webapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
