apiVersion: batch/v1
kind: Job
metadata:
  name: webapp-loadtest
  namespace: webapp
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hey
          image: rakyll/hey
          args: ["-z", "120s", "-c", "25", "http://webapp:3000/"]
